In [20]:
import pandas as pd 

archivo= pd.read_csv("../files/input/solicitudes_de_credito.csv",delimiter=";",index_col=0)

archivo.size

98280

## Limpieza

In [24]:
archivolimpio=archivo.copy()
filas_con_na = archivolimpio[archivo.duplicated()]
print(filas_con_na)
archivolimpio=archivolimpio.dropna()
archivolimpio=archivolimpio.drop_duplicates()
archivolimpio.drop
archivolimpio.size
archivolimpio

            sexo tipo_de_emprendimiento     idea_negocio  \
498     femenino               servicio  cafe e internet
1749    femenino               comercio       variedades
1754    femenino               comercio           tienda
1920   masculino               comercio       variedades
2065   masculino               comercio  cafe e internet
...          ...                    ...              ...
10865  masculino              industria      fabrica de
10881  masculino               comercio       miscelanea
10891   femenino               comercio       variedades
10909  masculino               comercio  comidas rapidas
10910   femenino               servicio        panaderia

                       barrio  estrato  comuna_ciudadano fecha_de_beneficio  \
498                   robledo        1               7.0         24/06/2016
1749                san pablo        1               1.0          1/11/2018
1754                carpinelo        1               1.0         30/10/2017
1920                 pablo vi        2               2.0         19/06/2018
2065               campo amor        2              15.0         24/08/2017
...                       ...      ...               ...                ...
10865       manrique oriental        2               3.0          4/05/2018
10881                castilla        3               5.0          8/05/2018
10891   cabecera san antonio         3              80.0         25/09/2017
10909              santa cruz        2               2.0         10/05/2018
10910  manrique central no. 1        2               4.0          5/09/2016

      monto_del_credito     línea_credito
498             6000000  microempresarial
1749            7000000  microempresarial
1754            1000000  microempresarial
1920            7000000  microempresarial
2065            7000000  microempresarial
...                 ...               ...
10865           7812000  microempresarial
10881           1500000  microempresarial
10891           7000000  microempresarial
10909           7800000  microempresarial
10910           6890000  microempresarial

[241 rows x 9 columns]

,sexo,tipo_de_emprendimiento,idea_negocio,barrio,estrato,comuna_ciudadano,fecha_de_beneficio,monto_del_credito,línea_credito
0,masculino,comercio,fabrica de,prado,3,10.0,13/07/2018,5000000,microempresarial
1,femenino,servicio,recreativo-educativo,barrio caicedo,1,9.0,30/10/2017,6000000,microempresarial
2,femenino,comercio,tienda,aranjuez,2,4.0,3/08/2017,7300000,microempresarial
3,Masculino,comercio,variedades,cabecera san cristobal,3,60.0,20/11/2017,7000000,microempresarial
4,femenino,comercio,fabrica de,robledo,2,7.0,23/02/2017,5000000,microempresarial
...,...,...,...,...,...,...,...,...,...
10915,masculino,agropecuaria,comidas rapidas,villatina,1,8.0,9/05/2018,7000000,microempresarial
10916,masculino,comercio,fabrica de arepas,villa hermosa,3,8.0,23/01/2017,7377000,microempresarial
10917,femenino,comercio,variedades,cabecera san cristobal,1,60.0,12/04/2018,7800000,microempresarial
10918,femenino,servicio,cafe e internet,manrique oriental,2,3.0,1/06/2017,7370000,microempresarial
10919,masculino,comercio,fabrica de helados,castilla,3,5.0,23/07/2018,7500000,microempresarial

In [22]:
import os 

if not os.path.exists ("../files/output/"):
    os.makedirs("../files/output/")

archivolimpio.to_csv("../files/output/solicitudes_de_credito.csv",sep=";",index=False)